name: PHP Linting
on: pull_request
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: aglipanci/laravel-pint-action@2.0.0
        name: "laravel-pint"
        with:
          preset: laravel
          verboseMode: true
          pintVersion: 1.13.7
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply pint changes